### ISSUE TITLE
Allow intersected sync paths with different parameters

### ISSUE THREAD

**Issue by hood-ok** [c-orter/ModSync#3]
Example of `config.jsonc`
```
{
	"syncPaths": [
		{
			"path": "BepInEx/config/FOVFix.cfg",
			"enabled": true,
			"enforced": false,
			"restartRequired": false
		},
		{
			"path": "BepInEx/config",
			"enabled": true,
			"enforced": true,
			"restartRequired": false
		}
	],
	"commonModExclusions": [
	]
}
```
The example aims to enforce sync of all files in `BepInEx/config` except `FOVFix.cfg`, which is not forced.
It should rely on the order in `syncPaths`: the higher the position - the higher the order.

With this change:
* It's not required to add all config files manually with an `enforced` parameter
* This will allow the update `BepInEx/config` files without touching files allowed to be modified by skipping the update (enforced files always be downloaded)

**Comment by c-orter** [comment]
Added with [v0.9.0](https://github.com/c-orter/ModSync/releases/tag/v0.9.0)
