### ISSUE TITLE
issue on client due to an empty folder from server not being created on the client

### ISSUE THREAD

**Issue by jonjetjon** [c-orter/ModSync#5]
We noticed an issue on our server that runs Amands' sense(the current version from https://github.com/Amands2Mello/AmandsSense not the outdated version from the spt hub) where the sense plugin requires an empty folder (bepinex/plugins/sense/sounds) to exist in order for the mod to function, but modsync does not make a copy of that empty folder on the client pc. This can obviously be fixed by the end user creating the folder themselves, but does cause an inconvenience when the point of modsync is to have as little end user interaction and setup as possible.

to resolve this issue it would be great to have the ability(optional or by default) to sync empty folders inside the sync paths.

**Comment by c-orter** [comment]
Fixed with [v0.9.0](https://github.com/c-orter/ModSync/releases/tag/v0.9.0)
